FROM python:alpine
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /usr/src/app
COPY requirements.txt ./
COPY entrypoint.sh ./
RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers bash
RUN apk add libffi-dev
RUN pip install -r requirements.txt
RUN chown -R root:root .
RUN chmod +x entrypoint.sh
RUN ls -al
CMD ["./entrypoint.sh"]